### PR TITLE
Added Mean Class

### LINKED ISSUE #46: Add program to find mean, median, mode of a array

### PR DESCRIPTION
**Pull request by KostasThan**
- [x] Add an Algorithm?
- [ ] Add a Data Structure?
- [ ] Add a Program not related to above?
- [ ] Fix a bug or typo in an existing cases?
- [ ] Documentation change?

#### References
For #46  **ONLY** added the Mean algorithm.

### **Checklist:**

- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by AkMo3** [comment]
Your are not following commit message format. The format is Fixes: #46 . And if pushing new commit updates then you need to squash merge them. I can't merge this as these commits contain previous commit messages of Median class. Also don't add .gitignore file. That file is unique in project and must occur one. Just don't track the class files before sending PR.

**Review by AkMo3 — CHANGES_REQUESTED** [review]
Delete Meadian.java and .gitignore from this PR.

**Comment by KostasThan** [comment]
I didn't to that 
> The format is Fixes: #46 . 

with the mindset that there are still thing to be done to fix the #46 issue. My bad.
As for 
> Also don't add .gitignore file.

Sorry. It's actually my third PR and I am new to this. Should i delete the PR and make it again; as i do not know how to change things here.

**Comment by AkMo3** [comment]
Try the following steps, it may work out. 
1. Remove the median.java and .gitignore file.
2. Commit the changes.
3. Squash previous commit into a single commit. Refer to this thread [Squash_Previous_commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git). I recommend the hard reset method because you can then edit the commit message to right format. Also, prepare for exams buddy. You can do these later also.

**Comment by AkMo3** [comment]
You deleted the wrong .gitignore xD. Delete the one present in NumberSystem directory. And add the deleted one.

**Review by AkMo3 — CHANGES_REQUESTED** [review]
Add this file again.

**Comment by AkMo3** [comment]
Better close this PR now, and make a new one with just Mean.java file in NumberSystem.

**Comment by KostasThan** [comment]
I did the 1,2 but i cannot do the third one with looooots of questions 😅 .  Plus i want to keep contributing to your repo so i guess i need to learn this thigs. Is there a discuss section or something? 
>Better close this PR now, and make a new one with just Mean.java file in NumberSystem.

I think this is the only thing i can do. 😅 .
Thanks for remembering my exams though!

**Comment by KostasThan** [comment]
It like i am a baby you babysit... 😆  I delete this one and make another.

**Comment by AkMo3** [comment]
No problem. In my first commit I had to close my PR for 4 consecutive times. This is just your first one. Also there is a gitter link in the of Readme. You can message there.

**Comment by KostasThan** [comment]
Yeah i will just ask you here couple of things so i do not spam elsewhere. 
For the new commit should i fork this repo again?
If a do fork it the Median class will be in there and you said 
>Remove the median.java

And another thing. In  my new PR in the number system there should be only the Median class and delete the other?
Please,feel free to not waste your time here answering me, as I search for this answers.

**Comment by AkMo3** [comment]
Yes, you can delete your earlier fork and fork a new one. That would contain your **Median class**. In your new PR just add the **Mean class** in NumberSystem and  don't delete anything ,leave the rest as it is.

**Pull request closed without merging**
